notifications:
  email:
    recipients:
      - rodrigo@kamada.com.br

language: generic

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: src
  on:
    branch: master
